apiVersion: v1
kind: Service
metadata:
  name: govee-server
  namespace: govee-server
  labels:
    app: govee-server
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "metrics-micrometer"
    prometheus.io/scheme: "http"
spec:
  selector:
    app: govee-server
  ports:
  - name: web
    port: 8080
    targetPort: 8080
