on: 
    workflow_dispatch: {}

name: Build Container

permissions: 
    contents: read
    packages: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up JDK 11
              uses: actions/setup-java@v3
              with:
                java-version: '11'
                distribution: 'temurin'
            - name: Make gradlew executable
              working-directory: server
              run: chmod +x gradlew
            - name: Setup gradle
              uses: gradle/actions/setup-gradle@v3
            - name: Execute Gradle build
              working-directory: server
              run: ./gradlew --no-daemon jibDockerBuild
            - name: Tag Image
              run: docker tag server ghcr.io/everbuild-org/govee-server:latest
            - name: Login to GitHub Container Registry
              run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u everbuild-org --password-stdin
            - name: Push Image
              run: docker push ghcr.io/everbuild-org/govee-server:latest